<script>
	import { fetchLandingPads } from '$lib/api';
	import { onMount } from 'svelte';
	import {
		Chart,
		Card,
		A,
		Button,
		Dropdown,
		DropdownItem,
		Popover,
		Tooltip
	} from 'flowbite-svelte';
	import {
		InfoCircleSolid,
		ArrowDownToBracketOutline,
		ChevronDownOutline,
		ChevronRightOutline,
		PenSolid,
		DownloadSolid,
		ShareNodesSolid
	} from 'flowbite-svelte-icons';

	let totalLandingPads = [];

	const options = {
		series: [],
		colors: ['#1C64F2', '#16BDCA', '#FDBA8C', '#E74694'],
		chart: {
			height: 320,
			width: '100%',
			type: 'donut'
		},
		stroke: {
			colors: ['transparent'],
			lineCap: ''
		},
		plotOptions: {
			pie: {
				donut: {
					labels: {
						show: true,
						name: {
							show: true,
							fontFamily: 'Inter, sans-serif',
							offsetY: 20
						},
						total: {
							showAlways: true,
							show: true,
							label: 'Landing Pads',
							fontFamily: 'Inter, sans-serif',
							formatter: function (w) {
								return `${totalLandingPads}`;
							}
						},
						value: {
							show: true,
							fontFamily: 'Inter, sans-serif',
							offsetY: -20,
							formatter: function (value) {
								return value + 'k';
							}
						}
					},
					size: '80%'
				}
			}
		},
		grid: {
			padding: {
				top: -2
			}
		},
		labels: [],
		dataLabels: {
			enabled: false
		},
		legend: {
			position: 'bottom',
			fontFamily: 'Inter, sans-serif'
		},
		yaxis: {
			labels: {
				formatter: function (value) {
					return value + 'k';
				}
			}
		},
		xaxis: {
			labels: {
				formatter: function (value) {
					return value + 'k';
				}
			},
			axisTicks: {
				show: false
			},
			axisBorder: {
				show: false
			}
		}
	};

	// Fetch data from API and calculate rates
	onMount(async () => {
		try {
			const response = await fetch('https://api.spacexdata.com/v3/landpads');
			const data = await response.json();
			totalLandingPads = data.length;
			// series calculation
			options.series = data.map((item) => {
				if (!item.attempted_landings || item.attempted_landings === 0) {
					// Handle invalid or zero attempted_landings
					console.warn(`Invalid or zero attempted_landings for item: ${item.full_name}`);
					return 0; // Or any fallback value
				}
				const successRate = (item.successful_landings / item.attempted_landings) * 100;
				return successRate;
			});

			options.labels = data.map((item) => item.full_name);
		} catch (error) {
			console.error('Error fetching chart data:', error);
		}
	});
</script>

<Card>
	<div class="flex w-full items-start justify-between">
		<div class="flex-col items-center">
			<div class="mb-1 flex items-center">
				<h5 class="me-1 text-xl font-bold leading-none text-gray-900 dark:text-white">
					Success Rate Chart
				</h5>
				<Popover
					triggeredBy="#donut1"
					class="z-10 w-72 rounded-lg border border-gray-200 bg-white text-sm text-gray-500 shadow-sm dark:border-gray-600 dark:bg-gray-800 dark:text-gray-400"
				>
					<div class="space-y-2 p-3">
						<h3 class="font-semibold text-gray-900 dark:text-white">
							Activity growth - Incremental
						</h3>
						<p>
							Report helps navigate cumulative growth of community activities. Ideally, the chart
							should have a growing trend, as stagnating chart signifies a significant decrease of
							community activity.
						</p>
						<h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
						<p>
							For each date bucket, the all-time volume of activities is calculated. This means that
							activities in period n contain all activities up to period n, plus the activities
							generated by your community in period.
						</p>
						<A href="/">Read more <ChevronRightOutline class="ms-1.5 h-2 w-2" /></A>
					</div>
				</Popover>
			</div>
		</div>
	</div>

	<Chart {options} class="py-6" />
</Card>
